version: '3'
services:
  mariadb:
    image: mariadb:10.6
    working_dir: /app
    volumes:
      - ./containers/mariadb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "46003:3306"

  webserver:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ./src:/app
      - ./containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "46000:80"

  php-fpm:
    build: containers/php-fpm
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./src:/app
